<RockSimDocument>
 <FileVersion>2</FileVersion>
 <DesignInformation>
  <RocketDesign>
   <Name>Lancer IV Block 1</Name>
   <CalculateCD>1</CalculateCD>
   <FixedCd>0.75</FixedCd>
   <FixedCd2>0.78</FixedCd2>
   <FixedCd3>0.8</FixedCd3>
   <StageCount>1</StageCount>
   <Stage3Mass>0.</Stage3Mass>
   <Stage2Mass>0.</Stage2Mass>
   <Stage1Mass>0.</Stage1Mass>
   <Stage321CG>0.</Stage321CG>
   <Stage32CG>0.</Stage32CG>
   <Stage3CG>0.</Stage3CG>
   <CPCalcFlags>5</CPCalcFlags>
   <LaunchGuideLength>914.4</LaunchGuideLength>
   <UseKnownMass>0</UseKnownMass>
   <DefaultFinish>1</DefaultFinish>
   <FinishMedium>0</FinishMedium>
   <FinishCoatCount>2</FinishCoatCount>
   <GlueType>0</GlueType>
   <Comments></Comments>
   <Designer></Designer>
   <CPSimFlags>1</CPSimFlags>
   <LastSerialNumber>25</LastSerialNumber>
   <DisplayFlags>1</DisplayFlags>
   <MetricsFlags>0</MetricsFlags>
   <CameraState></CameraState>
   <BarromanXN>0.,1579.86081251026,0.,0.</BarromanXN>
   <BarrowmanCNa>0.,16.6315374096367,0.,0.</BarrowmanCNa>
   <RockSimXN>0.,1637.75455716425,0.,0.</RockSimXN>
   <RockSimCNa>0.,23.6307973983293,0.,0.</RockSimCNa>
   <ViewType>0</ViewType>
   <ViewStageCount>1</ViewStageCount>
   <ViewTypeEdit>0</ViewTypeEdit>
   <ViewStageCountEdit>1</ViewStageCountEdit>
   <ZoomFactor>0.</ZoomFactor>
   <ZoomFactorEdit>0.</ZoomFactorEdit>
   <ScrollPosX>0</ScrollPosX>
   <ScrollPosY>0</ScrollPosY>
   <ScrollPosXEdit>0</ScrollPosXEdit>
   <ScrollPosYEdit>0</ScrollPosYEdit>
   <ThreeDFlags>0</ThreeDFlags>
   <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
   <SimulationEventList>
    <SimulationEvent>
     <PartSerialNo>17</PartSerialNo>
     <Type>4</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>0</HasDeployed>
     <DeployedAt_Altitude>0.</DeployedAt_Altitude>
     <DeployedAt_Velocity>0.</DeployedAt_Velocity>
     <DeployedAt_Range>0.</DeployedAt_Range>
     <DeployedAt_Time>0.</DeployedAt_Time>
     <DeviceID>-1</DeviceID>
    </SimulationEvent>
   </SimulationEventList>
   <Stage3Parts>
    <NoseCone>
     <PartMfg>LOC Precision</PartMfg>
     <KnownMass>141.748</KnownMass>
     <Density>1049.2093265</Density>
     <Material>Polystyrene PS</Material>
     <Name>Nose cone</Name>
     <KnownCG>209.55</KnownCG>
     <UseKnownCG>1</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>339.40515555926</CalcMass>
     <CalcCG>264.401968200678</CalcCG>
     <WettedSurface>6.99236956967394e-002</WettedSurface>
     <PaintedSurface>6.99236956967394e-002</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>LOC PNC-3.90</PartNo>
     <PartDesc>Plastic nose cone</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>1</SerialNo>
     <DisplayFlags>8</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>2.</BarrowmanCNa>
     <BarrowmanXN>0.149920668616551</BarrowmanXN>
     <RockSimCNa>2.</RockSimCNa>
     <RockSimXN>0.149920668616551</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <Len>323.85</Len>
     <BaseDia>101.6</BaseDia>
     <FinishCode>1</FinishCode>
     <ShapeCode>1</ShapeCode>
     <ConstructionType>1</ConstructionType>
     <ShoulderLen>95.25</ShoulderLen>
     <WallThickness>3.175</WallThickness>
     <ShapeParameter>0.</ShapeParameter>
     <ShoulderOD>98.425</ShoulderOD>
     <PointList></PointList>
     <BaseExtensionLen>0.</BaseExtensionLen>
     <CoreDia>0.</CoreDia>
     <CoreLen>0.</CoreLen>
     <AttachedParts>
     </AttachedParts>
    </NoseCone>
    <BodyTube>
     <PartMfg>Public Missiles Ltd.</PartMfg>
     <KnownMass>0.</KnownMass>
     <Density>958.70501055</Density>
     <Material>Kraft phenolic</Material>
     <Name>Body tube</Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>0</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>218.258266079951</CalcMass>
     <CalcCG>228.6</CalcCG>
     <WettedSurface>0.146807919057593</WettedSurface>
     <PaintedSurface>0.146807919057593</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>PT-3.9</PartNo>
     <PartDesc>Airframe tube</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>2</SerialNo>
     <DisplayFlags>1</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <OD>102.21</OD>
     <ID>99.06</ID>
     <Len>457.2</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>0.</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
      <BodyTube>
       <PartMfg>Public Missiles Ltd.</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>958.70501055</Density>
       <Material>Kraft phenolic</Material>
       <Name>Body tube</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>-88.9</Xb>
       <CalcMass>140.951008223145</CalcMass>
       <CalcCG>152.4</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>CT-3.9</PartNo>
       <PartDesc>Coupler tube</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>9</SerialNo>
       <DisplayFlags>9</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>99.06</OD>
       <ID>95.91</ID>
       <Len>304.8</Len>
       <FinishCode>1</FinishCode>
       <IsMotorMount>0</IsMotorMount>
       <MotorDia>0.</MotorDia>
       <EngineOverhang>12.7</EngineOverhang>
       <FrontExtension>0.</FrontExtension>
       <RearExtension>0.</RearExtension>
       <IsInsideTube>1</IsInsideTube>
       <AttachedParts>
        <Ring>
         <PartMfg>Public Missiles</PartMfg>
         <KnownMass>0.</KnownMass>
         <Density>680.7846775</Density>
         <Material>Birch</Material>
         <Name>Bulkhead</Name>
         <KnownCG>0.</KnownCG>
         <UseKnownCG>0</UseKnownCG>
         <Xb>3.175</Xb>
         <CalcMass>23.4265328525111</CalcMass>
         <CalcCG>2.3815</CalcCG>
         <WettedSurface>0.</WettedSurface>
         <PaintedSurface>0.</PaintedSurface>
         <GlueJointLength>0.</GlueJointLength>
         <DensityType>0</DensityType>
         <PartNo>CBP-3.9</PartNo>
         <PartDesc>Was CBP-06</PartDesc>
         <RadialLoc>0.</RadialLoc>
         <RadialAngle>0.</RadialAngle>
         <Texture></Texture>
         <Opacity>1.</Opacity>
         <Specular>0.</Specular>
         <SpecularPower>1.</SpecularPower>
         <Ambient>0.</Ambient>
         <Diffuse>1.</Diffuse>
         <AbientColor>0,0,250</AbientColor>
         <DiffuseColor>0,0,250</DiffuseColor>
         <SpecularColor>255,255,255</SpecularColor>
         <UseSingleColor>1</UseSingleColor>
         <SerialNo>16</SerialNo>
         <DisplayFlags>8</DisplayFlags>
         <MetricsFlags>0</MetricsFlags>
         <LocationMode>2</LocationMode>
         <Color>0,0,250</Color>
         <BarrowmanCNa>0.</BarrowmanCNa>
         <BarrowmanXN>0.</BarrowmanXN>
         <RockSimCNa>0.</RockSimCNa>
         <RockSimXN>0.</RockSimXN>
         <SimpleColorModel>1</SimpleColorModel>
         <OD>95.91</OD>
         <ID>0.</ID>
         <Len>4.763</Len>
         <FinishCode>0</FinishCode>
         <UsageCode>1</UsageCode>
         <AutoSize>1</AutoSize>
         <AttachedParts>
         </AttachedParts>
        </Ring>
        <MassObject>
         <PartMfg>Custom</PartMfg>
         <KnownMass>96.388</KnownMass>
         <Density>0.</Density>
         <Material></Material>
         <Name>Missileworks RRC2X</Name>
         <KnownCG>0.</KnownCG>
         <UseKnownCG>1</UseKnownCG>
         <Xb>203.2</Xb>
         <CalcMass>0.</CalcMass>
         <CalcCG>0.</CalcCG>
         <WettedSurface>0.</WettedSurface>
         <PaintedSurface>0.</PaintedSurface>
         <GlueJointLength>0.</GlueJointLength>
         <DensityType>0</DensityType>
         <PartNo></PartNo>
         <PartDesc></PartDesc>
         <RadialLoc>0.</RadialLoc>
         <RadialAngle>0.</RadialAngle>
         <Texture></Texture>
         <Opacity>1.</Opacity>
         <Specular>0.</Specular>
         <SpecularPower>1.</SpecularPower>
         <Ambient>0.</Ambient>
         <Diffuse>1.</Diffuse>
         <AbientColor>0,0,250</AbientColor>
         <DiffuseColor>0,0,250</DiffuseColor>
         <SpecularColor>255,255,255</SpecularColor>
         <UseSingleColor>1</UseSingleColor>
         <SerialNo>18</SerialNo>
         <DisplayFlags>8</DisplayFlags>
         <MetricsFlags>0</MetricsFlags>
         <LocationMode>0</LocationMode>
         <Color>0,0,250</Color>
         <BarrowmanCNa>0.</BarrowmanCNa>
         <BarrowmanXN>0.</BarrowmanXN>
         <RockSimCNa>0.</RockSimCNa>
         <RockSimXN>0.</RockSimXN>
         <SimpleColorModel>1</SimpleColorModel>
         <TypeCode>0</TypeCode>
         <Len>0.</Len>
         <AttachedParts>
         </AttachedParts>
        </MassObject>
       </AttachedParts>
      </BodyTube>
     </AttachedParts>
    </BodyTube>
    <BodyTube>
     <PartMfg>Public Missiles Ltd.</PartMfg>
     <KnownMass>0.</KnownMass>
     <Density>958.70501055</Density>
     <Material>Kraft phenolic</Material>
     <Name>Body tube</Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>0</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>363.763776799919</CalcMass>
     <CalcCG>381.</CalcCG>
     <WettedSurface>0.244679865095989</WettedSurface>
     <PaintedSurface>0.244679865095989</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>PT-3.9</PartNo>
     <PartDesc>Airframe tube</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>3</SerialNo>
     <DisplayFlags>9</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <OD>102.21</OD>
     <ID>99.06</ID>
     <Len>762.</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>12.7</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
      <Parachute>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>9.1519390826e-005</Density>
       <Material>1.9 oz. Ripstop Nylon (SkyAngle)</Material>
       <Name>Parachute</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>304.8</Xb>
       <CalcMass>1.50303141155147</CalcMass>
       <CalcCG>127.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>1</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>17</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <Dia>1524.</Dia>
       <SpillHoleDia>0.</SpillHoleDia>
       <SideCount>8</SideCount>
       <ShroudLineCount>8</ShroudLineCount>
       <Thickness>0.</Thickness>
       <ShroudLineLen>1219.2</ShroudLineLen>
       <ChuteCount>1</ChuteCount>
       <ShroudLineMassPerMM>0.</ShroudLineMassPerMM>
       <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
       <DragCoefficient>0.75</DragCoefficient>
       <AttachedParts>
       </AttachedParts>
      </Parachute>
      <MassObject>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>153.087</KnownMass>
       <Density>1.6741845735e-002</Density>
       <Material>9/16 In. tubular nylon</Material>
       <Name>Shock cord</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>1</UseKnownCG>
       <Xb>203.2</Xb>
       <CalcMass>153.08743740084</CalcMass>
       <CalcCG>0.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>2</DensityType>
       <PartNo>SCTN-30</PartNo>
       <PartDesc>Tubular Nylon  9/16 In x 30 Ft</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>25</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <TypeCode>1</TypeCode>
       <Len>9144.</Len>
       <AttachedParts>
       </AttachedParts>
      </MassObject>
     </AttachedParts>
    </BodyTube>
    <BodyTube>
     <PartMfg>Public Missiles Ltd.</PartMfg>
     <KnownMass>0.</KnownMass>
     <Density>958.70501055</Density>
     <Material>Kraft phenolic</Material>
     <Name>Body tube</Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>0</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>242.509184533279</CalcMass>
     <CalcCG>254.</CalcCG>
     <WettedSurface>0.163119910063993</WettedSurface>
     <PaintedSurface>0.163119910063993</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>PT-3.9</PartNo>
     <PartDesc>Airframe tube</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>4</SerialNo>
     <DisplayFlags>1</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <OD>102.21</OD>
     <ID>99.06</ID>
     <Len>508.</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>0.</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
      <BodyTube>
       <PartMfg>Public Missiles Ltd.</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>958.70501055</Density>
       <Material>Kraft phenolic</Material>
       <Name>Body tube</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>76.2</Xb>
       <CalcMass>99.5670875863264</CalcMass>
       <CalcCG>260.35</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>PT-1.5</PartNo>
       <PartDesc>Airframe tube</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>7</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>41.885</OD>
       <ID>38.735</ID>
       <Len>520.7</Len>
       <FinishCode>3</FinishCode>
       <IsMotorMount>1</IsMotorMount>
       <MotorDia>38.</MotorDia>
       <EngineOverhang>12.7</EngineOverhang>
       <FrontExtension>0.</FrontExtension>
       <RearExtension>0.</RearExtension>
       <IsInsideTube>1</IsInsideTube>
       <AttachedParts>
       </AttachedParts>
      </BodyTube>
      <FinSet>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>424.4892695</Density>
       <Material>Basswood</Material>
       <Name>Fin set</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>25.4</Xb>
       <CalcMass>304.466673133446</CalcMass>
       <CalcCG>268.347212105694</CalcCG>
       <WettedSurface>7.74192e-002</WettedSurface>
       <PaintedSurface>0.2322576</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>8</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>14.6315374096367</BarrowmanCNa>
       <BarrowmanXN>1.77532081153291</BarrowmanXN>
       <RockSimCNa>21.6307973983293</RockSimCNa>
       <RockSimXN>1.77532081153291</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <FinCount>3</FinCount>
       <RootChord>457.2</RootChord>
       <TipChord>50.8</TipChord>
       <SemiSpan>152.4</SemiSpan>
       <MidChordLen>214.444082655945</MidChordLen>
       <SweepDistance>354.065849635197</SweepDistance>
       <Thickness>4.7625</Thickness>
       <ShapeCode>0</ShapeCode>
       <FinishCode>1</FinishCode>
       <TipShapeCode>2</TipShapeCode>
       <TabLength>381.</TabLength>
       <TabDepth>30.1625</TabDepth>
       <TabOffset>25.4</TabOffset>
       <SweepMode>0</SweepMode>
       <SweepAngle>1.04719758</SweepAngle>
       <AttachedParts>
       </AttachedParts>
      </FinSet>
      <BodyTube>
       <PartMfg>Public Missiles Ltd.</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>958.70501055</Density>
       <Material>Kraft phenolic</Material>
       <Name>Body tube</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>-88.9</Xb>
       <CalcMass>82.2214214635012</CalcMass>
       <CalcCG>88.9</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>CT-3.9</PartNo>
       <PartDesc>Coupler tube</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>10</SerialNo>
       <DisplayFlags>1</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>99.06</OD>
       <ID>95.91</ID>
       <Len>177.8</Len>
       <FinishCode>1</FinishCode>
       <IsMotorMount>0</IsMotorMount>
       <MotorDia>0.</MotorDia>
       <EngineOverhang>0.</EngineOverhang>
       <FrontExtension>0.</FrontExtension>
       <RearExtension>0.</RearExtension>
       <IsInsideTube>1</IsInsideTube>
       <AttachedParts>
       </AttachedParts>
      </BodyTube>
      <Ring>
       <PartMfg>Public Missiles</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (Birch)</Material>
       <Name>Ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>76.2</Xb>
       <CalcMass>21.8555480939467</CalcMass>
       <CalcCG>2.3815</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>CR-3.9-1.5</PartNo>
       <PartDesc>Was PML CR-13</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>11</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>99.06</OD>
       <ID>41.885</ID>
       <Len>4.763</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <Ring>
       <PartMfg>Public Missiles</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (Birch)</Material>
       <Name>Ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>457.2</Xb>
       <CalcMass>21.8555480939467</CalcMass>
       <CalcCG>2.3815</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>CR-3.9-1.5</PartNo>
       <PartDesc>Was PML CR-13</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>12</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>99.06</OD>
       <ID>41.885</ID>
       <Len>4.763</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <Ring>
       <PartMfg>Public Missiles</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (Birch)</Material>
       <Name>Ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>-82.55</Xb>
       <CalcMass>21.8555480939467</CalcMass>
       <CalcCG>2.3815</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>CCR-3.9-1.5</PartNo>
       <PartDesc>Was PML CCR-13</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>13</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>99.06</OD>
       <ID>41.885</ID>
       <Len>4.763</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <MassObject>
       <PartMfg>Public Missiles</PartMfg>
       <KnownMass>5.67</KnownMass>
       <Density>0.</Density>
       <Material>Steel</Material>
       <Name>Eye Bolt</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>1</UseKnownCG>
       <Xb>-101.6</Xb>
       <CalcMass>0.</CalcMass>
       <CalcCG>0.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>HDWE-EYE-1/8</PartNo>
       <PartDesc>1/8x24</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>23</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <TypeCode>0</TypeCode>
       <Len>0.</Len>
       <AttachedParts>
       </AttachedParts>
      </MassObject>
     </AttachedParts>
    </BodyTube>
   </Stage3Parts>
   <Stage2Parts>
   </Stage2Parts>
   <Stage1Parts>
   </Stage1Parts>
  </RocketDesign>
 </DesignInformation>
 <SimulationResultsList>
  <SimulationResults>
   <MaxAltitude>762.910421524904</MaxAltitude>
   <MaxVelocity>149.435364823991</MaxVelocity>
   <MaxAcceleration>149.541209425172</MaxAcceleration>
   <TimeToApogee>11.7800000000014</TimeToApogee>
   <OptimalDelay>9.57875000000142</OptimalDelay>
   <MultiDelayCount>0</MultiDelayCount>
   <VelocityAtDeplyment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>2.20124999999999</TimeToBurnout>
   <TimeToLanding>137.218749999893</TimeToLanding>
   <TimeToEject>0.</TimeToEject>
   <MinLaunchGuideLen>0.741939951304242</MinLaunchGuideLen>
   <MaxVertVelocity>149.389678427075</MaxVertVelocity>
   <MaxHorzVelocity>0.884761873228859</MaxHorzVelocity>
   <MaxVertAcceleration>149.541209425172</MaxVertAcceleration>
   <MaxHorzAcceleration>0.583024835730465</MaxHorzAcceleration>
   <MaxRange>157.18348033932</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>1.570796</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>0.</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>2</LaunchWindPreset>
   <LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[I211W-None] </SimulationName>
   <VelocityAtLaunchGuideEnd>14.8177326036221</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.11625</TimeToFreeFlight>
   <TimeToMaxVelocity>1.86874999999997</TimeToMaxVelocity>
   <TimeToMaxAcceleration>1.25e-003</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>2.23903143024283</ExecutionTime>
   <RangeAtLanding>157.18348033932</RangeAtLanding>
   <VelocityAtLanding>7.09566742514258</VelocityAtLanding>
   <XVelcoityAtLanding>0.496954260164204</XVelcoityAtLanding>
   <YVelocityAtLanding>-7.07824361487609</YVelocityAtLanding>
   <StageEjectTime>-1.,-1.,1.6e+308</StageEjectTime>
   <TimeToDeployment>0.,0.,11.7800000000014</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>2.41542662636547</Mass0>
   <CG0>1.33257553154704</CG0>
   <LaterialMOI0>0.93229319294321</LaterialMOI0>
   <RadialMOI0>5.34826326316545e-003</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>17</PartSerialNo>
     <Type>4</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>762.910419948537</DeployedAt_Altitude>
     <DeployedAt_Velocity>2.00957743307712</DeployedAt_Velocity>
     <DeployedAt_Range>-25.6586899173022</DeployedAt_Range>
     <DeployedAt_Time>11.7800000000014</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>I211W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>7</MountSerialNo>
     <EjectionDelay>-2.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>367.250698154945</MaxAltitude>
   <MaxVelocity>91.8380336360589</MaxVelocity>
   <MaxAcceleration>119.008419761007</MaxAcceleration>
   <TimeToApogee>8.58749999999978</TimeToApogee>
   <OptimalDelay>7.3862499999998</OptimalDelay>
   <MultiDelayCount>0</MultiDelayCount>
   <VelocityAtDeplyment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>1.20124999999998</TimeToBurnout>
   <TimeToLanding>78.4974999999467</TimeToLanding>
   <TimeToEject>0.</TimeToEject>
   <MinLaunchGuideLen>0.844341854385834</MinLaunchGuideLen>
   <MaxVertVelocity>91.8374363667966</MaxVertVelocity>
   <MaxHorzVelocity>0.473136170674055</MaxHorzVelocity>
   <MaxVertAcceleration>119.008419761007</MaxVertAcceleration>
   <MaxHorzAcceleration>3.28211129390597e-002</MaxHorzAcceleration>
   <MaxRange>42.8424140455574</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>1.570796</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>0.</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>2</LaunchWindPreset>
   <LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[H242T-None] </SimulationName>
   <VelocityAtLaunchGuideEnd>14.1373616922311</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.1275</TimeToFreeFlight>
   <TimeToMaxVelocity>1.13499999999998</TimeToMaxVelocity>
   <TimeToMaxAcceleration>1.25e-003</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>1.27686639590607</ExecutionTime>
   <RangeAtLanding>42.8424140455574</RangeAtLanding>
   <VelocityAtLanding>5.2570035410765</VelocityAtLanding>
   <XVelcoityAtLanding>0.473141749142789</XVelcoityAtLanding>
   <YVelocityAtLanding>-5.23566835428954</YVelocityAtLanding>
   <StageEjectTime>-1.,-1.,1.6e+308</StageEjectTime>
   <TimeToDeployment>0.,0.,8.58749999999978</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>2.21822662636547</Mass0>
   <CG0>1.29150030321106</CG0>
   <LaterialMOI0>0.912781796194188</LaterialMOI0>
   <RadialMOI0>3.87437088224585e-003</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>17</PartSerialNo>
     <Type>4</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>367.25069163565</DeployedAt_Altitude>
     <DeployedAt_Velocity>0.23666278603694</DeployedAt_Velocity>
     <DeployedAt_Range>-2.08513413976159</DeployedAt_Range>
     <DeployedAt_Time>8.58749999999978</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>H242T</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>7</MountSerialNo>
     <EjectionDelay>-2.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>938.393458743026</MaxAltitude>
   <MaxVelocity>188.705705247152</MaxVelocity>
   <MaxAcceleration>184.418715165285</MaxAcceleration>
   <TimeToApogee>12.4900000000018</TimeToApogee>
   <OptimalDelay>10.6887500000018</OptimalDelay>
   <MultiDelayCount>0</MultiDelayCount>
   <VelocityAtDeplyment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>1.80124999999997</TimeToBurnout>
   <TimeToLanding>184.64124999985</TimeToLanding>
   <TimeToEject>0.</TimeToEject>
   <MinLaunchGuideLen>0.556657432128387</MinLaunchGuideLen>
   <MaxVertVelocity>188.683732053208</MaxVertVelocity>
   <MaxHorzVelocity>0.656725831717039</MaxHorzVelocity>
   <MaxVertAcceleration>184.418715165285</MaxVertAcceleration>
   <MaxHorzAcceleration>0.575800815948344</MaxHorzAcceleration>
   <MaxRange>85.2069744322635</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>1.570796</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>0.</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>2</LaunchWindPreset>
   <LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[I284W-None] </SimulationName>
   <VelocityAtLaunchGuideEnd>17.3483308247744</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.1025</TimeToFreeFlight>
   <TimeToMaxVelocity>1.57249999999997</TimeToMaxVelocity>
   <TimeToMaxAcceleration>1.25e-003</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>2.93803292372832</ExecutionTime>
   <RangeAtLanding>85.2069744322635</RangeAtLanding>
   <VelocityAtLanding>5.34271996681808</VelocityAtLanding>
   <XVelcoityAtLanding>2.52218587270573e-002</XVelcoityAtLanding>
   <YVelocityAtLanding>-5.34266043293778</YVelocityAtLanding>
   <StageEjectTime>-1.,-1.,1.6e+308</StageEjectTime>
   <TimeToDeployment>0.,0.,12.4900000000018</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>2.50692662636547</Mass0>
   <CG0>1.34659643008223</CG0>
   <LaterialMOI0>0.936464232548644</LaterialMOI0>
   <RadialMOI0>6.6319280933796e-003</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>17</PartSerialNo>
     <Type>4</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>938.393456999454</DeployedAt_Altitude>
     <DeployedAt_Velocity>1.32194416839654</DeployedAt_Velocity>
     <DeployedAt_Range>-19.3542278934694</DeployedAt_Range>
     <DeployedAt_Time>12.4900000000018</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>I284W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>7</MountSerialNo>
     <EjectionDelay>-2.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>1140.85967259011</MaxAltitude>
   <MaxVelocity>226.450959951548</MaxVelocity>
   <MaxAcceleration>260.844757355217</MaxAcceleration>
   <TimeToApogee>13.2887500000022</TimeToApogee>
   <OptimalDelay>11.3875000000022</OptimalDelay>
   <MultiDelayCount>0</MultiDelayCount>
   <VelocityAtDeplyment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>1.90124999999997</TimeToBurnout>
   <TimeToLanding>219.854999999818</TimeToLanding>
   <TimeToEject>0.</TimeToEject>
   <MinLaunchGuideLen>0.375726563618759</MinLaunchGuideLen>
   <MaxVertVelocity>226.449776536957</MaxVertVelocity>
   <MaxHorzVelocity>0.893981799409033</MaxHorzVelocity>
   <MaxVertAcceleration>260.844757355217</MaxVertAcceleration>
   <MaxHorzAcceleration>0.164045467270448</MaxHorzAcceleration>
   <MaxRange>255.461979232482</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>1.570796</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>0.</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>2</LaunchWindPreset>
   <LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[J350W-None] </SimulationName>
   <VelocityAtLaunchGuideEnd>20.8067930977396</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>8.5e-002</TimeToFreeFlight>
   <TimeToMaxVelocity>1.51124999999997</TimeToMaxVelocity>
   <TimeToMaxAcceleration>1.25e-003</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>3.51545195955018</ExecutionTime>
   <RangeAtLanding>255.461979232482</RangeAtLanding>
   <VelocityAtLanding>5.53218941047007</VelocityAtLanding>
   <XVelcoityAtLanding>0.893981916494207</XVelcoityAtLanding>
   <YVelocityAtLanding>-5.45947946294319</YVelocityAtLanding>
   <StageEjectTime>-1.,-1.,1.6e+308</StageEjectTime>
   <TimeToDeployment>0.,0.,13.2887500000022</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>2.60412662636547</Mass0>
   <CG0>1.35948711928918</CG0>
   <LaterialMOI0>0.939924607159682</LaterialMOI0>
   <RadialMOI0>8.32172948804175e-003</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>17</PartSerialNo>
     <Type>4</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>1140.85966599707</DeployedAt_Altitude>
     <DeployedAt_Velocity>0.296089390649387</DeployedAt_Velocity>
     <DeployedAt_Range>-5.12804530775192</DeployedAt_Range>
     <DeployedAt_Time>13.2887500000022</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>J350W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>A-RMS</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>7</MountSerialNo>
     <EjectionDelay>-2.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
 </SimulationResultsList>
</RockSimDocument>
