<RockSimDocument>
 <FileVersion>2</FileVersion>
 <DesignInformation>
  <RocketDesign>
   <Name></Name>
   <CalculateCD>1</CalculateCD>
   <FixedCd>0.75</FixedCd>
   <FixedCd2>0.78</FixedCd2>
   <FixedCd3>0.8</FixedCd3>
   <StageCount>1</StageCount>
   <Stage3Mass>0.</Stage3Mass>
   <Stage2Mass>0.</Stage2Mass>
   <Stage1Mass>0.</Stage1Mass>
   <Stage321CG>0.</Stage321CG>
   <Stage32CG>0.</Stage32CG>
   <Stage3CG>0.</Stage3CG>
   <CPCalcFlags>1</CPCalcFlags>
   <LaunchGuideLength>914.4</LaunchGuideLength>
   <UseKnownMass>0</UseKnownMass>
   <DefaultFinish>1</DefaultFinish>
   <FinishMedium>0</FinishMedium>
   <FinishCoatCount>2</FinishCoatCount>
   <GlueType>0</GlueType>
   <Comments></Comments>
   <Designer></Designer>
   <CPSimFlags>1</CPSimFlags>
   <LastSerialNumber>24</LastSerialNumber>
   <DisplayFlags>1</DisplayFlags>
   <MetricsFlags>0</MetricsFlags>
   <CameraState></CameraState>
   <BarromanXN>0.,1651.30375248756,0.,0.</BarromanXN>
   <BarrowmanCNa>0.,12.4692098684865,0.,0.</BarrowmanCNa>
   <RockSimXN>0.,1751.91393281878,0.,0.</RockSimXN>
   <RockSimCNa>0.,18.4692108081357,0.,0.</RockSimCNa>
   <ViewType>0</ViewType>
   <ViewStageCount>1</ViewStageCount>
   <ViewTypeEdit>0</ViewTypeEdit>
   <ViewStageCountEdit>1</ViewStageCountEdit>
   <ZoomFactor>0.</ZoomFactor>
   <ZoomFactorEdit>0.</ZoomFactorEdit>
   <ScrollPosX>0</ScrollPosX>
   <ScrollPosY>0</ScrollPosY>
   <ScrollPosXEdit>0</ScrollPosXEdit>
   <ScrollPosYEdit>0</ScrollPosYEdit>
   <ThreeDFlags>0</ThreeDFlags>
   <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
   <SimulationEventList>
    <SimulationEvent>
     <PartSerialNo>10</PartSerialNo>
     <Type>5</Type>
     <DeployAltitude>609.6</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>0</HasDeployed>
     <DeployedAt_Altitude>0.</DeployedAt_Altitude>
     <DeployedAt_Velocity>0.</DeployedAt_Velocity>
     <DeployedAt_Range>0.</DeployedAt_Range>
     <DeployedAt_Time>0.</DeployedAt_Time>
     <DeviceID>-1</DeviceID>
    </SimulationEvent>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>4</Type>
     <DeployAltitude>609.6</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>0</HasDeployed>
     <DeployedAt_Altitude>0.</DeployedAt_Altitude>
     <DeployedAt_Velocity>0.</DeployedAt_Velocity>
     <DeployedAt_Range>0.</DeployedAt_Range>
     <DeployedAt_Time>0.</DeployedAt_Time>
     <DeviceID>-1</DeviceID>
    </SimulationEvent>
   </SimulationEventList>
   <Stage3Parts>
    <NoseCone>
     <PartMfg>Custom</PartMfg>
     <KnownMass>481.941891</KnownMass>
     <Density>128.147704</Density>
     <Material>Fiberglass</Material>
     <Name>5:1 Von Karmann FNC</Name>
     <KnownCG>330.2</KnownCG>
     <UseKnownCG>1</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>55.5649474552652</CalcMass>
     <CalcCG>342.998937688115</CalcCG>
     <WettedSurface>0.11184057725796</WettedSurface>
     <PaintedSurface>0.11184057725796</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo></PartNo>
     <PartDesc></PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>1</SerialNo>
     <DisplayFlags>8</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>2.</BarrowmanCNa>
     <BarrowmanXN>0.195573795354213</BarrowmanXN>
     <RockSimCNa>2.</RockSimCNa>
     <RockSimXN>0.195573795354213</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <Len>482.6</Len>
     <BaseDia>101.6</BaseDia>
     <FinishCode>1</FinishCode>
     <ShapeCode>6</ShapeCode>
     <ConstructionType>1</ConstructionType>
     <ShoulderLen>76.2</ShoulderLen>
     <WallThickness>3.175</WallThickness>
     <ShapeParameter>0.5</ShapeParameter>
     <ShoulderOD>98.425</ShoulderOD>
     <PointList></PointList>
     <BaseExtensionLen>0.</BaseExtensionLen>
     <CoreDia>0.</CoreDia>
     <CoreLen>0.</CoreLen>
     <AttachedParts>
     </AttachedParts>
    </NoseCone>
    <BodyTube>
     <PartMfg>Giant Leap</PartMfg>
     <KnownMass>0.</KnownMass>
     <Density>1905.23598922</Density>
     <Material>G10 fiberglass</Material>
     <Name><![CDATA[Fiberglass 4" BT]]></Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>0</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>279.658150758534</CalcMass>
     <CalcCG>152.4</CalcCG>
     <WettedSurface>9.77742751794198e-002</WettedSurface>
     <PaintedSurface>9.77742751794198e-002</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>B-3.90-L</PartNo>
     <PartDesc>3.90 BT</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>2</SerialNo>
     <DisplayFlags>9</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <OD>102.108</OD>
     <ID>99.06</ID>
     <Len>304.8</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>12.7</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
     </AttachedParts>
    </BodyTube>
    <BodyTube>
     <PartMfg>Custom</PartMfg>
     <KnownMass>0.</KnownMass>
     <Density>1905.23598922</Density>
     <Material>G10 fiberglass</Material>
     <Name><![CDATA[Fiberglass 4" BT]]></Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>0</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>256.029626446759</CalcMass>
     <CalcCG>152.4</CalcCG>
     <WettedSurface>9.75310555894213e-002</WettedSurface>
     <PaintedSurface>9.75310555894213e-002</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo></PartNo>
     <PartDesc></PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>4</SerialNo>
     <DisplayFlags>9</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <OD>101.854</OD>
     <ID>99.06</ID>
     <Len>304.8</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>12.7</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
      <BodyTube>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>1905.23598922</Density>
       <Material>G10 fiberglass</Material>
       <Name><![CDATA[4" Fiberglass Coupler]]></Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>-101.6</Xb>
       <CalcMass>466.853603956025</CalcMass>
       <CalcCG>254.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>5</SerialNo>
       <DisplayFlags>9</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>99.06</OD>
       <ID>95.91</ID>
       <Len>508.</Len>
       <FinishCode>1</FinishCode>
       <IsMotorMount>0</IsMotorMount>
       <MotorDia>0.</MotorDia>
       <EngineOverhang>12.7</EngineOverhang>
       <FrontExtension>0.</FrontExtension>
       <RearExtension>0.</RearExtension>
       <IsInsideTube>1</IsInsideTube>
       <AttachedParts>
        <Ring>
         <PartMfg>Custom</PartMfg>
         <KnownMass>0.</KnownMass>
         <Density>1905.23598922</Density>
         <Material>G10 fiberglass</Material>
         <Name>Bulkhead</Name>
         <KnownCG>0.</KnownCG>
         <UseKnownCG>0</UseKnownCG>
         <Xb>4.7625</Xb>
         <CalcMass>65.5612192347686</CalcMass>
         <CalcCG>2.3815</CalcCG>
         <WettedSurface>0.</WettedSurface>
         <PaintedSurface>0.</PaintedSurface>
         <GlueJointLength>0.</GlueJointLength>
         <DensityType>0</DensityType>
         <PartNo></PartNo>
         <PartDesc></PartDesc>
         <RadialLoc>0.</RadialLoc>
         <RadialAngle>0.</RadialAngle>
         <Texture></Texture>
         <Opacity>1.</Opacity>
         <Specular>0.</Specular>
         <SpecularPower>1.</SpecularPower>
         <Ambient>0.</Ambient>
         <Diffuse>1.</Diffuse>
         <AbientColor>0,0,250</AbientColor>
         <DiffuseColor>0,0,250</DiffuseColor>
         <SpecularColor>255,255,255</SpecularColor>
         <UseSingleColor>1</UseSingleColor>
         <SerialNo>8</SerialNo>
         <DisplayFlags>8</DisplayFlags>
         <MetricsFlags>0</MetricsFlags>
         <LocationMode>0</LocationMode>
         <Color>0,0,250</Color>
         <BarrowmanCNa>0.</BarrowmanCNa>
         <BarrowmanXN>0.</BarrowmanXN>
         <RockSimCNa>0.</RockSimCNa>
         <RockSimXN>0.</RockSimXN>
         <SimpleColorModel>1</SimpleColorModel>
         <OD>95.91</OD>
         <ID>0.</ID>
         <Len>4.763</Len>
         <FinishCode>0</FinishCode>
         <UsageCode>1</UsageCode>
         <AutoSize>1</AutoSize>
         <AttachedParts>
         </AttachedParts>
        </Ring>
        <Ring>
         <PartMfg>Custom</PartMfg>
         <KnownMass>0.</KnownMass>
         <Density>1905.23598922</Density>
         <Material>G10 fiberglass</Material>
         <Name>Bulkhead</Name>
         <KnownCG>0.</KnownCG>
         <UseKnownCG>0</UseKnownCG>
         <Xb>4.7625</Xb>
         <CalcMass>65.5612192347686</CalcMass>
         <CalcCG>2.3815</CalcCG>
         <WettedSurface>0.</WettedSurface>
         <PaintedSurface>0.</PaintedSurface>
         <GlueJointLength>0.</GlueJointLength>
         <DensityType>0</DensityType>
         <PartNo></PartNo>
         <PartDesc></PartDesc>
         <RadialLoc>0.</RadialLoc>
         <RadialAngle>0.</RadialAngle>
         <Texture></Texture>
         <Opacity>1.</Opacity>
         <Specular>0.</Specular>
         <SpecularPower>1.</SpecularPower>
         <Ambient>0.</Ambient>
         <Diffuse>1.</Diffuse>
         <AbientColor>0,0,250</AbientColor>
         <DiffuseColor>0,0,250</DiffuseColor>
         <SpecularColor>255,255,255</SpecularColor>
         <UseSingleColor>1</UseSingleColor>
         <SerialNo>9</SerialNo>
         <DisplayFlags>8</DisplayFlags>
         <MetricsFlags>0</MetricsFlags>
         <LocationMode>2</LocationMode>
         <Color>0,0,250</Color>
         <BarrowmanCNa>0.</BarrowmanCNa>
         <BarrowmanXN>0.</BarrowmanXN>
         <RockSimCNa>0.</RockSimCNa>
         <RockSimXN>0.</RockSimXN>
         <SimpleColorModel>1</SimpleColorModel>
         <OD>95.91</OD>
         <ID>0.</ID>
         <Len>4.763</Len>
         <FinishCode>0</FinishCode>
         <UsageCode>1</UsageCode>
         <AutoSize>1</AutoSize>
         <AttachedParts>
         </AttachedParts>
        </Ring>
       </AttachedParts>
      </BodyTube>
     </AttachedParts>
    </BodyTube>
    <BodyTube>
     <PartMfg>Custom</PartMfg>
     <KnownMass>0.</KnownMass>
     <Density>1905.23598922</Density>
     <Material>G10 fiberglass</Material>
     <Name><![CDATA[Fiberglass 4" BT]]></Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>0</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>559.316301517067</CalcMass>
     <CalcCG>304.8</CalcCG>
     <WettedSurface>0.19554855035884</WettedSurface>
     <PaintedSurface>0.19554855035884</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo></PartNo>
     <PartDesc></PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>6</SerialNo>
     <DisplayFlags>9</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <OD>102.108</OD>
     <ID>99.06</ID>
     <Len>609.6</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>12.7</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
      <Parachute>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>9.1519390826e-005</Density>
       <Material>1.9 oz. Ripstop Nylon (SkyAngle)</Material>
       <Name>Parachute</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>104.775</Xb>
       <CalcMass>3.1246428881762</CalcMass>
       <CalcCG>177.8</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>1</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>10</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <Dia>2133.6</Dia>
       <SpillHoleDia>0.</SpillHoleDia>
       <SideCount>12</SideCount>
       <ShroudLineCount>12</ShroudLineCount>
       <Thickness>0.</Thickness>
       <ShroudLineLen>1828.8</ShroudLineLen>
       <ChuteCount>1</ChuteCount>
       <ShroudLineMassPerMM>0.</ShroudLineMassPerMM>
       <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
       <DragCoefficient>0.75</DragCoefficient>
       <AttachedParts>
       </AttachedParts>
      </Parachute>
      <Streamer>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>9.1519390826e-005</Density>
       <Material>1.9 oz. Ripstop Nylon (SkyAngle)</Material>
       <Name>Streamer</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>444.5</Xb>
       <CalcMass>0.188942880592967</CalcMass>
       <CalcCG>50.8</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>1</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>255,0,0</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>11</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>255,0,0</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <Len>2032.</Len>
       <Width>101.6</Width>
       <Thickness>5.08e-002</Thickness>
       <StreamerCount>1</StreamerCount>
       <DragCoefficient>0.320181818181818</DragCoefficient>
       <IsFolded>1</IsFolded>
       <AutoCalcCd>1</AutoCalcCd>
       <AttachedParts>
       </AttachedParts>
      </Streamer>
     </AttachedParts>
    </BodyTube>
    <BodyTube>
     <PartMfg>Giant Leap</PartMfg>
     <KnownMass>0.</KnownMass>
     <Density>958.70501055</Density>
     <Material>Kraft phenolic</Material>
     <Name>Body tube</Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>0</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>193.249198875549</CalcMass>
     <CalcCG>228.6</CalcCG>
     <WettedSurface>0.146296583384132</WettedSurface>
     <PaintedSurface>0.146296583384132</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>B-3.90</PartNo>
     <PartDesc>3.90 BT</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>15</SerialNo>
     <DisplayFlags>9</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <OD>101.854</OD>
     <ID>99.06</ID>
     <Len>457.2</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>12.7</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
      <BodyTube>
       <PartMfg>Giant Leap</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>958.70501055</Density>
       <Material>Kraft phenolic</Material>
       <Name>Body tube</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>-50.8</Xb>
       <CalcMass>146.09503478238</CalcMass>
       <CalcCG>285.75</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>B-2.152</PartNo>
       <PartDesc>54mm BT</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>18</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>57.683</OD>
       <ID>54.661</ID>
       <Len>571.5</Len>
       <FinishCode>1</FinishCode>
       <IsMotorMount>1</IsMotorMount>
       <MotorDia>54.</MotorDia>
       <EngineOverhang>12.7</EngineOverhang>
       <FrontExtension>0.</FrontExtension>
       <RearExtension>0.</RearExtension>
       <IsInsideTube>1</IsInsideTube>
       <AttachedParts>
       </AttachedParts>
      </BodyTube>
      <Ring>
       <PartMfg>Public Missiles</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (Birch)</Material>
       <Name>Ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>12.7</Xb>
       <CalcMass>17.5894803454659</CalcMass>
       <CalcCG>2.3815</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>CR-3.9-2.1</PartNo>
       <PartDesc>Was PML CR-14</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>19</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>99.06</OD>
       <ID>57.683</ID>
       <Len>4.763</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <Ring>
       <PartMfg>Public Missiles</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (Birch)</Material>
       <Name>Ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>508.</Xb>
       <CalcMass>2.56878141236801</CalcMass>
       <CalcCG>2.3815</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>CCR-3.9-2.1</PartNo>
       <PartDesc>Was PML CCR-14</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>20</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>65.3795381587105</OD>
       <ID>57.683</ID>
       <Len>4.763</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <BodyTube>
       <PartMfg>Public Missiles Ltd.</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>958.70501055</Density>
       <Material>Kraft phenolic</Material>
       <Name>Body tube</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>-63.5</Xb>
       <CalcMass>82.2214214635012</CalcMass>
       <CalcCG>88.9</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>CT-3.9</PartNo>
       <PartDesc>Coupler tube</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>22</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>99.06</OD>
       <ID>95.91</ID>
       <Len>177.8</Len>
       <FinishCode>1</FinishCode>
       <IsMotorMount>0</IsMotorMount>
       <MotorDia>0.</MotorDia>
       <EngineOverhang>12.7</EngineOverhang>
       <FrontExtension>0.</FrontExtension>
       <RearExtension>0.</RearExtension>
       <IsInsideTube>1</IsInsideTube>
       <AttachedParts>
       </AttachedParts>
      </BodyTube>
      <Ring>
       <PartMfg>Public Missiles</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (Birch)</Material>
       <Name>Ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>228.6</Xb>
       <CalcMass>17.5894803454659</CalcMass>
       <CalcCG>2.3815</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>CR-3.9-2.1</PartNo>
       <PartDesc>Was PML CR-14</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>23</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>99.06</OD>
       <ID>57.683</ID>
       <Len>4.763</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <FinSet>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>128.147704</Density>
       <Material>Balsa</Material>
       <Name>Fin set</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>107.95</Xb>
       <CalcMass>51.961953778792</CalcMass>
       <CalcCG>211.670546052818</CalcCG>
       <WettedSurface>5.67607852614536e-002</WettedSurface>
       <PaintedSurface>0.170282355784361</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>24</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>11.8457999984559</BarrowmanCNa>
       <BarrowmanXN>1.96100214231656</BarrowmanXN>
       <RockSimCNa>17.8458009381051</RockSimCNa>
       <RockSimXN>1.96100214231656</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <FinCount>3</FinCount>
       <RootChord>350.52</RootChord>
       <TipChord>71.12</TipChord>
       <SemiSpan>134.62</SemiSpan>
       <MidChordLen>163.886977478566</MidChordLen>
       <SweepDistance>233.168695224979</SweepDistance>
       <Thickness>4.7625</Thickness>
       <ShapeCode>0</ShapeCode>
       <FinishCode>1</FinishCode>
       <TipShapeCode>1</TipShapeCode>
       <TabLength>0.</TabLength>
       <TabDepth>0.</TabDepth>
       <TabOffset>0.</TabOffset>
       <SweepMode>0</SweepMode>
       <SweepAngle>1.04719758</SweepAngle>
       <AttachedParts>
       </AttachedParts>
      </FinSet>
     </AttachedParts>
    </BodyTube>
    <Transition>
     <PartMfg>Public Missiles</PartMfg>
     <KnownMass>0.225</KnownMass>
     <Density>1905.23598922</Density>
     <Material>G10 fiberglass</Material>
     <Name>Transition</Name>
     <KnownCG>15.697</KnownCG>
     <UseKnownCG>0</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>296.47712817286</CalcMass>
     <CalcCG>24.7641895713301</CalcCG>
     <WettedSurface>1.89945979808333e-002</WettedSurface>
     <PaintedSurface>1.89945979808333e-002</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>TC-3.9-2.1</PartNo>
     <PartDesc>Transition (or tailcone) from 3.9 to 2.1</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>17</SerialNo>
     <DisplayFlags>8</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>-1.37659012996941</BarrowmanCNa>
     <BarrowmanXN>2.20133331830199</BarrowmanXN>
     <RockSimCNa>-1.37659012996941</RockSimCNa>
     <RockSimXN>2.20133331830199</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <FrontDia>102.21</FrontDia>
     <RearDia>57.81</RearDia>
     <Len>63.5</Len>
     <FinishCode>1</FinishCode>
     <FrontShoulderLen>6.35</FrontShoulderLen>
     <RearShoulderLen>0.</RearShoulderLen>
     <ConstructionType>1</ConstructionType>
     <WallThickness>5.715</WallThickness>
     <FrontShoulderDia>99.06</FrontShoulderDia>
     <RearShoulderDia>0.</RearShoulderDia>
     <CoreDia>0.</CoreDia>
     <ShapeCode>3</ShapeCode>
     <ShapeParameter>0.</ShapeParameter>
     <EquivNoseLen>76.9991760253906</EquivNoseLen>
     <EquivNoseOffset>13.4991760253906</EquivNoseOffset>
     <AttachedParts>
     </AttachedParts>
    </Transition>
   </Stage3Parts>
   <Stage2Parts>
   </Stage2Parts>
   <Stage1Parts>
   </Stage1Parts>
  </RocketDesign>
 </DesignInformation>
 <SimulationResultsList>
  <SimulationResults>
   <MaxAltitude>2619.14055442825</MaxAltitude>
   <MaxVelocity>398.274852671451</MaxVelocity>
   <MaxAcceleration>370.909804023029</MaxAcceleration>
   <TimeToApogee>19.8437500000001</TimeToApogee>
   <OptimalDelay>17.38375</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>357.676493704389,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>631.586490636577,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>2.46000000000003,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>2.46000000000003</TimeToBurnout>
   <TimeToLanding>186.542499999848</TimeToLanding>
   <TimeToEject>2.46000000000003</TimeToEject>
   <MinLaunchGuideLen>0.37069754429119</MinLaunchGuideLen>
   <MaxVertVelocity>398.247868027488</MaxVertVelocity>
   <MaxHorzVelocity>0.894079999999988</MaxHorzVelocity>
   <MaxVertAcceleration>370.909803960134</MaxVertAcceleration>
   <MaxHorzAcceleration>1.39147832064165</MaxHorzAcceleration>
   <MaxRange>208.515874953168</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>1.570796</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>0.</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>2</LaunchWindPreset>
   <LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[K1050W-0   ] </SimulationName>
   <VelocityAtLaunchGuideEnd>21.5505237156543</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>9.00000000000001e-002</TimeToFreeFlight>
   <TimeToMaxVelocity>1.99999999999996</TimeToMaxVelocity>
   <TimeToMaxAcceleration>82.8349999999428</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>3.2130923865764</ExecutionTime>
   <RangeAtLanding>208.515874953168</RangeAtLanding>
   <VelocityAtLanding>6.68966937454355</VelocityAtLanding>
   <XVelcoityAtLanding>0.457090219653571</XVelcoityAtLanding>
   <YVelocityAtLanding>-6.67403512665336</YVelocityAtLanding>
   <StageEjectTime>-1.,-1.,2.46</StageEjectTime>
   <TimeToDeployment>0.,0.,19.8437500000001</TimeToDeployment>
   <DeploymentType>32,32,83</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>5.24498807709307</Mass0>
   <CG0>1.49726510539576</CG0>
   <LaterialMOI0>1.89338364741744</LaterialMOI0>
   <RadialMOI0>6.37030307158128e-002</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>10</PartSerialNo>
     <Type>5</Type>
     <DeployAltitude>609.6</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>609.578383657834</DeployedAt_Altitude>
     <DeployedAt_Velocity>31.6284264242685</DeployedAt_Velocity>
     <DeployedAt_Range>70.1495517385362</DeployedAt_Range>
     <DeployedAt_Time>82.8337499999428</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>4</Type>
     <DeployAltitude>609.6</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>2619.14055056191</DeployedAt_Altitude>
     <DeployedAt_Velocity>1.62576677815488</DeployedAt_Velocity>
     <DeployedAt_Range>-40.4965891274913</DeployedAt_Range>
     <DeployedAt_Time>19.8437500000001</DeployedAt_Time>
     <DeviceID>8</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>K1050W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>18</MountSerialNo>
     <EjectionDelay>0.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>2389.23775583767</MaxAltitude>
   <MaxVelocity>378.977806986205</MaxVelocity>
   <MaxAcceleration>370.844646760727</MaxAcceleration>
   <TimeToApogee>18.9900000000009</TimeToApogee>
   <OptimalDelay>16.9887500000009</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>348.003391136638,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>486.22338692874,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>2.00124999999996,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>2.00124999999996</TimeToBurnout>
   <TimeToLanding>199.808749999836</TimeToLanding>
   <TimeToEject>2.00124999999996</TimeToEject>
   <MinLaunchGuideLen>0.380531974540689</MinLaunchGuideLen>
   <MaxVertVelocity>378.977380035968</MaxVertVelocity>
   <MaxHorzVelocity>0.865019779787113</MaxHorzVelocity>
   <MaxVertAcceleration>370.844646760708</MaxVertAcceleration>
   <MaxHorzAcceleration>0.19513971972432</MaxHorzAcceleration>
   <MaxRange>198.688979850877</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>1.570796</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>0.</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>2</LaunchWindPreset>
   <LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[K1275R-0   ] </SimulationName>
   <VelocityAtLaunchGuideEnd>22.0064009886881</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.10375</TimeToFreeFlight>
   <TimeToMaxVelocity>1.71624999999997</TimeToMaxVelocity>
   <TimeToMaxAcceleration>76.2449999999488</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>3.41784237442402</ExecutionTime>
   <RangeAtLanding>198.688979850877</RangeAtLanding>
   <VelocityAtLanding>4.91348065768126</VelocityAtLanding>
   <XVelcoityAtLanding>0.865021761612223</XVelcoityAtLanding>
   <YVelocityAtLanding>-4.8367374877437</YVelocityAtLanding>
   <StageEjectTime>-1.,-1.,2.</StageEjectTime>
   <TimeToDeployment>0.,0.,18.9900000000009</TimeToDeployment>
   <DeploymentType>32,32,83</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>5.04698807709307</Mass0>
   <CG0>1.49474508574495</CG0>
   <LaterialMOI0>1.90310886286311</LaterialMOI0>
   <RadialMOI0>4.83946538381343e-002</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>10</PartSerialNo>
     <Type>5</Type>
     <DeployAltitude>609.6</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>609.562909934405</DeployedAt_Altitude>
     <DeployedAt_Velocity>31.0699501869753</DeployedAt_Velocity>
     <DeployedAt_Range>30.5456736952791</DeployedAt_Range>
     <DeployedAt_Time>76.2437499999488</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>4</Type>
     <DeployAltitude>609.6</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>2389.23774136299</DeployedAt_Altitude>
     <DeployedAt_Velocity>0.202093480342777</DeployedAt_Velocity>
     <DeployedAt_Range>-5.06462286896456</DeployedAt_Range>
     <DeployedAt_Time>18.9900000000009</DeployedAt_Time>
     <DeviceID>8</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>K1275R</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AeroTech</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>18</MountSerialNo>
     <EjectionDelay>0.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>2109.98687826701</MaxAltitude>
   <MaxVelocity>226.799583933033</MaxVelocity>
   <MaxAcceleration>370.786735325965</MaxAcceleration>
   <TimeToApogee>20.6537499999993</TimeToApogee>
   <OptimalDelay>13.1524999999998</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>180.031688940489,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>1121.82223464267,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>7.50124999999958,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>7.50124999999958</TimeToBurnout>
   <TimeToLanding>195.89499999984</TimeToLanding>
   <TimeToEject>7.50124999999958</TimeToEject>
   <MinLaunchGuideLen>2.75743859363731</MinLaunchGuideLen>
   <MaxVertVelocity>226.786509981006</MaxVertVelocity>
   <MaxHorzVelocity>0.187729327202317</MaxHorzVelocity>
   <MaxVertAcceleration>370.786735284094</MaxVertAcceleration>
   <MaxHorzAcceleration>0.205165305460896</MaxHorzAcceleration>
   <MaxRange>31.9193489352437</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>1.570796</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>0.</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>2</LaunchWindPreset>
   <LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[K185W-0   ] </SimulationName>
   <VelocityAtLaunchGuideEnd>7.49171610844821</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.25</TimeToFreeFlight>
   <TimeToMaxVelocity>5.14000000000005</TimeToMaxVelocity>
   <TimeToMaxAcceleration>70.3062499999542</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>3.41355384174418</ExecutionTime>
   <RangeAtLanding>-12.2323234711702</RangeAtLanding>
   <VelocityAtLanding>4.76329817077989</VelocityAtLanding>
   <XVelcoityAtLanding>0.187733879054908</XVelcoityAtLanding>
   <YVelocityAtLanding>-4.75959719455439</YVelocityAtLanding>
   <StageEjectTime>-1.,-1.,7.5</StageEjectTime>
   <TimeToDeployment>0.,0.,20.6537499999993</TimeToDeployment>
   <DeploymentType>32,32,83</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>4.40348807709307</Mass0>
   <CG0>1.45556176463624</CG0>
   <LaterialMOI0>1.85620528271129</LaterialMOI0>
   <RadialMOI0>2.13656964580751e-002</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>10</PartSerialNo>
     <Type>5</Type>
     <DeployAltitude>609.6</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>609.56717662308</DeployedAt_Altitude>
     <DeployedAt_Velocity>30.5691729920787</DeployedAt_Velocity>
     <DeployedAt_Range>-24.9356882851703</DeployedAt_Range>
     <DeployedAt_Time>70.3049999999542</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>4</Type>
     <DeployAltitude>609.6</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>2109.98686666567</DeployedAt_Altitude>
     <DeployedAt_Velocity>1.35731820280749</DeployedAt_Velocity>
     <DeployedAt_Range>-31.9193489352437</DeployedAt_Range>
     <DeployedAt_Time>20.6537499999993</DeployedAt_Time>
     <DeviceID>8</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>K185W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>18</MountSerialNo>
     <EjectionDelay>0.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
 </SimulationResultsList>
</RockSimDocument>
